name: Build and Publish

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Jar
    runs-on: ubuntu-latest
    env:
      OS_GRPC_URL: grpc://object-store-v2.p8e:80
      PROVENANCE_GRPC_URL: grpc://192.168.1.244:9090
      TEST_ENCRYPTION_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
      TEST_SIGNING_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
      PROD_ENCRYPTION_PRIVATE_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
      PROD_SIGNING_PRIVATE_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
      TEST_CHAIN_ID: pio-testnet-1
      PROD_CHAIN_ID: pio-mainnet-1

    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Gradle
        run: ./gradlew clean build --refresh-dependencies -Pversion=$VERSION
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Contract Syntax
        run: ./gradlew p8eClean p8eCheck --info

        # in order to bootstrap in github actions - we must have an object-store and query node that we can hit
      - name: Bootstrap Test
        run: CHAIN_ID=$TEST_CHAIN_ID ENCRYPTION_PRIVATE_KEY=$TEST_ENCRYPTION_PRIVATE_KEY SIGNING_PRIVATE_KEY=$TEST_SIGNING_PRIVATE_KEY ./gradlew p8eBootstrap --info

#      - name: Bootstrap Prod
#        run: CHAIN_ID=$PROD_CHAIN_ID ENCRYPTION_PRIVATE_KEY=$PROD_ENCRYPTION_PRIVATE_KEY SIGNING_PRIVATE_KEY=$PROD_SIGNING_PRIVATE_KEY ./gradlew p8eBootstrap --info